Enable env var hints for `--token`
fastly/cli pull request #945
Opened 2023-06-01 07:03 UTC by andersjanmyr

Example:

```
$ ./fastly list service --token $FASTLY<tab>
$FASTLY_ACCOUNT_DEV         $FASTLY_ACCOUNT_SALJA_PROD
$FASTLY_ACCOUNT_PROD        $FASTLY_ACCOUNT_SANDBOX
$FASTLY_ACCOUNT_SALJA_DEV
```

2023-06-01 12:05 UTC, Integralist requested changes
👋🏻 @andersjanmyr thanks for opening this PR! 

Implementation looks OK, I just have a few requests.

2023-06-01 13:18 UTC, andersjanmyr commented on pkg/app/run.go
> +var envVarCache []string
Yes, makes sense. I was thinking it was the same invokation every time I press tab, but it's a new every time.

2023-06-01 13:19 UTC, andersjanmyr commented on pkg/app/run.go
> +		envVarCache = append(envVarCache, fmt.Sprintf("\\$%s", pair[0]))
Yes, it probably needs some special treatment to handle Windows.

2023-06-01 14:34 UTC, Integralist commented
@andersjanmyr out of interest, is there a reason you're using this approach rather than something like `--profile` (e.g. `fastly service list --profile personal`)?

2023-06-01 15:17 UTC, andersjanmyr commented
@Integralist I was thinking of using profile locally, but we're using the same script to deploy both locally and on CI.
Something like this.
```
case "$env" in
  prod|stage)
    export FASTLY_API_KEY=$FASTLY_ACCOUNT_PROD
    ;;
  main)
    env='dev'
    export FASTLY_API_KEY=$FASTLY_ACCOUNT_DEV
    ;;
  *)
    export FASTLY_API_KEY=$FASTLY_ACCOUNT_DEV
    ;;
esac
```

2023-06-05 08:47 UTC, Integralist requested changes
Other than two minor change requests this looks good to me.

Thanks!

2023-06-05 08:47 UTC, Integralist commented on pkg/env/env.go
> +func Vars() []string {
We should annotate this public function.

2023-06-05 08:47 UTC, Integralist commented on pkg/env/env.go
> +	if runtime.GOOS == "windows" {
For consistency could we replace this with https://github.com/fastly/cli/blob/main/pkg/runtime/runtime.go#L11

2023-06-05 12:36 UTC, merged